global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'api-primary'
    static_configs:
      - targets: ['api-primary:5000']
  - job_name: 'api-standby-1'
    static_configs:
      - targets: ['api-standby-1:5000']
  - job_name: 'api-standby-2'
    static_configs:
      - targets: ['api-standby-2:5000']
